name: yqy1
channels:
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - alsa-plugins=1.2.12=h702c2b0_1
  - aom=3.9.1=hac33072_0
  - attr=2.5.1=h166bdaf_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cudatoolkit=11.4.3=h39f8164_13
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - faiss-gpu=1.7.4=py3.8_hc0239a3_0_cuda11.4
  - ffmpeg=7.1.1=gpl_hf9d4f8e_507
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.12=h7b179bb_1
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=h5888daf_0
  - harfbuzz=11.3.3=hbb57e21_0
  - icu=75.1=he02047a_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jack=1.9.22=hf4617a5_3
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.24.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.8.0=17_openblas
  - libcap=2.75=h39aace5_0
  - libcblas=3.8.0=17_openblas
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libfaiss=1.7.4=h13c3c6d_0_cuda11.4
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.8.0=17_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.10=pthreads_hb3c22a3_5
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h9ef548d_1
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.3=hee844dc_1
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=hf01ce69_5
  - libudev1=257.7=hbe16f8c_0
  - libunwind=1.8.2=h1441ba7_0
  - liburing=2.11=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - mkl=2025.0.0=hacee8c2_941
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h2d0b736_3
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openssl=3.5.1=h7b32b05_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.45=hc749103_0
  - pixman=0.46.4=h537e5f6_0
  - portaudio=19.6.0=h7c63dc7_9
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - python=3.8.20=h4a871b0_2_cpython
  - python_abi=3.8=8_cp38
  - readline=8.2=h8c095d6_2
  - sdl2=2.32.54=h3f2d84a_0
  - sdl3=3.2.18=h68140b3_0
  - snappy=1.2.2=h03e3b7b_0
  - svt-av1=3.0.2=h5888daf_0
  - tbb=2022.2.0=hb60516a_0
  - tbb-devel=2022.2.0=h74b38a2_0
  - tk=8.6.13=noxft_hd72426e_102
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.5.2
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.3
      - bidict==0.23.1
      - blinker==1.8.2
      - cachetools==5.5.2
      - catkin-pkg==1.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.1.1
      - cryptography==45.0.5
      - cycler==0.12.1
      - dashscope==1.24.1
      - distro==1.9.0
      - docutils==0.20.1
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - facenet-pytorch==2.6.0
      - faiss-cpu==1.8.0.post1
      - filelock==3.16.1
      - fire==0.7.0
      - flask==3.0.3
      - flask-cors==5.0.0
      - flask-socketio==5.5.1
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gast==0.4.0
      - gdown==5.2.0
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.11.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.5
      - jiter==0.9.1
      - joblib==1.4.2
      - keras==2.11.0
      - keyboard==0.13.5
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mediapipe==0.10.11
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mtcnn==0.1.1
      - multidict==6.1.0
      - networkx==3.1
      - numpy==1.24.3
      - numpysocket==1.0.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - openai==1.97.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.2.0
      - pip==25.0.1
      - propcache==0.2.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyaudio==0.2.14
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygame==2.6.1
      - pynput==1.8.1
      - pyparsing==3.1.4
      - pyrealsense2==2.55.1.6486
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.1
      - python-socketio==5.13.0
      - python-xlib==0.33
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - retina-face==0.0.17
      - rospkg==1.6.0
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentence-transformers==3.2.1
      - setuptools==75.3.2
      - simple-websocket==1.1.0
      - six==1.17.0
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - sympy==1.13.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.2.3
      - wave==0.0.2
      - webrtcvad==2.0.10
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - wsproto==1.2.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/zxr/.conda/envs/yqy1
